using System.Text;
using Restate.Sdk.Generators.Models;

namespace Restate.Sdk.Generators.Emitters;

internal static class ClientEmitter
{
    private const string CallOptionsType = "global::Restate.Sdk.CallOptions";

    public static string Generate(ServiceInfo service)
    {
        var sb = new StringBuilder(2048);
        var isKeyed = service.Kind == ServiceKind.VirtualObject || service.Kind == ServiceKind.Workflow;

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(service.Namespace))
        {
            sb.AppendLine($"namespace {service.Namespace};");
            sb.AppendLine();
        }

        // Call interface — I{Service}Client
        sb.AppendLine($"public interface I{service.ClassName}Client");
        sb.AppendLine("{");
        foreach (var handler in service.Handlers)
        {
            var returnType = handler.OutputTypeFullName is not null
                ? $"global::System.Threading.Tasks.ValueTask<{handler.OutputTypeFullName}>"
                : "global::System.Threading.Tasks.ValueTask";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";
            var optionsParam = inputParam.Length > 0
                ? $"{inputParam}, {CallOptionsType} options"
                : $"{CallOptionsType} options";
            sb.AppendLine($"    {returnType} {handler.Name}Async({inputParam});");
            sb.AppendLine($"    {returnType} {handler.Name}Async({optionsParam});");

            // Future method — non-blocking, for concurrent patterns
            if (handler.OutputTypeFullName is not null)
            {
                var futureReturnType = $"global::Restate.Sdk.IDurableFuture<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    {futureReturnType} {handler.Name}Future({inputParam});");
                sb.AppendLine($"    {futureReturnType} {handler.Name}Future({optionsParam});");
            }
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Send interface — I{Service}SendClient
        sb.AppendLine($"public interface I{service.ClassName}SendClient");
        sb.AppendLine("{");
        foreach (var handler in service.Handlers)
        {
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";
            sb.AppendLine(
                $"    global::System.Threading.Tasks.ValueTask<global::Restate.Sdk.InvocationHandle> {handler.Name}Send({inputParam});");
        }

        sb.AppendLine("}");
        sb.AppendLine();

        // Call implementation
        EmitCallClient(sb, service, isKeyed);
        sb.AppendLine();

        // Send implementation
        EmitSendClient(sb, service, isKeyed);

        return sb.ToString();
    }

    private static void EmitCallClient(StringBuilder sb, ServiceInfo service, bool isKeyed)
    {
        sb.AppendLine($"internal sealed class {service.ClassName}Client : I{service.ClassName}Client");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Restate.Sdk.Context _context;");
        if (isKeyed)
            sb.AppendLine("    private readonly string _key;");
        sb.AppendLine();

        if (isKeyed)
        {
            sb.AppendLine(
                $"    public {service.ClassName}Client(global::Restate.Sdk.Context context, string key)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _key = key;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine($"    public {service.ClassName}Client(global::Restate.Sdk.Context context)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("    }");
        }

        foreach (var handler in service.Handlers)
        {
            sb.AppendLine();
            // The request is always passed as object? so the call binds to the untyped overload
            // even when the handler's input is a string, which would otherwise be ambiguous with
            // the keyed overload.
            var requestArg = handler.InputTypeFullName is not null ? "(object?)request" : "(object?)null";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";
            var optionsParam = inputParam.Length > 0
                ? $"{inputParam}, {CallOptionsType} options"
                : $"{CallOptionsType} options";
            var target = isKeyed
                ? $"\"{service.ServiceName}\", _key, \"{handler.Name}\""
                : $"\"{service.ServiceName}\", \"{handler.Name}\"";

            if (handler.OutputTypeFullName is not null)
            {
                var returnType = $"global::System.Threading.Tasks.ValueTask<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    public {returnType} {handler.Name}Async({inputParam})");
                sb.AppendLine(
                    $"        => _context.Call<{handler.OutputTypeFullName}>({target}, {requestArg});");

                sb.AppendLine();
                sb.AppendLine($"    public {returnType} {handler.Name}Async({optionsParam})");
                sb.AppendLine(
                    $"        => _context.Call<{handler.OutputTypeFullName}>({target}, {requestArg}, options);");

                // Future methods
                sb.AppendLine();
                var futureReturnType = $"global::Restate.Sdk.IDurableFuture<{handler.OutputTypeFullName}>";
                sb.AppendLine($"    public {futureReturnType} {handler.Name}Future({inputParam})");
                sb.AppendLine(
                    $"        => _context.CallFuture<{handler.OutputTypeFullName}>({target}, {requestArg});");

                sb.AppendLine();
                sb.AppendLine($"    public {futureReturnType} {handler.Name}Future({optionsParam})");
                sb.AppendLine(
                    $"        => _context.CallFuture<{handler.OutputTypeFullName}>({target}, {requestArg}, options);");
            }
            else
            {
                EmitVoidCall(sb, handler.Name, inputParam, target, requestArg, null);
                sb.AppendLine();
                EmitVoidCall(sb, handler.Name, optionsParam, target, requestArg, "options");
            }
        }

        sb.AppendLine("}");
    }

    /// <summary>Emits a void-returning call method, optionally forwarding call options.</summary>
    private static void EmitVoidCall(StringBuilder sb, string handlerName, string parameters, string target,
        string requestArg, string? optionsArg)
    {
        var options = optionsArg is null ? "" : $", {optionsArg}";
        sb.AppendLine($"    public global::System.Threading.Tasks.ValueTask {handlerName}Async({parameters})");
        sb.AppendLine("    {");
        sb.AppendLine($"        var task = _context.Call<object?>({target}, {requestArg}{options});");
        sb.AppendLine(
            "        return task.IsCompletedSuccessfully ? default : new global::System.Threading.Tasks.ValueTask(task.AsTask());");
        sb.AppendLine("    }");
    }

    private static void EmitSendClient(StringBuilder sb, ServiceInfo service, bool isKeyed)
    {
        sb.AppendLine($"internal sealed class {service.ClassName}SendClient : I{service.ClassName}SendClient");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Restate.Sdk.Context _context;");
        if (isKeyed)
            sb.AppendLine("    private readonly string _key;");
        sb.AppendLine("    private readonly global::Restate.Sdk.SendOptions? _options;");
        sb.AppendLine();

        if (isKeyed)
        {
            sb.AppendLine(
                $"    public {service.ClassName}SendClient(global::Restate.Sdk.Context context, string key, global::Restate.Sdk.SendOptions? options)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _key = key;");
            sb.AppendLine("        _options = options;");
            sb.AppendLine("    }");
        }
        else
        {
            sb.AppendLine(
                $"    public {service.ClassName}SendClient(global::Restate.Sdk.Context context, global::Restate.Sdk.SendOptions? options)");
            sb.AppendLine("    {");
            sb.AppendLine("        _context = context;");
            sb.AppendLine("        _options = options;");
            sb.AppendLine("    }");
        }

        foreach (var handler in service.Handlers)
        {
            sb.AppendLine();
            var requestArg = handler.InputTypeFullName is not null ? "(object?)request" : "(object?)null";
            var inputParam = handler.InputTypeFullName is not null
                ? $"{handler.InputTypeFullName} request"
                : "";

            sb.AppendLine(
                $"    public global::System.Threading.Tasks.ValueTask<global::Restate.Sdk.InvocationHandle> {handler.Name}Send({inputParam})");

            // Passing the SendOptions whole carries the scope and limit key too, not just the
            // delay and idempotency key.
            if (isKeyed)
                sb.AppendLine(
                    $"        => _context.Send(\"{service.ServiceName}\", _key, \"{handler.Name}\", {requestArg}, _options ?? default);");
            else
                sb.AppendLine(
                    $"        => _context.Send(\"{service.ServiceName}\", \"{handler.Name}\", {requestArg}, _options ?? default);");
        }

        sb.AppendLine("}");
    }
}