//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace Restate.Sdk.FSharp.Samples

open System.Threading.Tasks
open Restate.Sdk.Hosting
open Restate.Sdk.FSharp

/// Restate registration generated from the [<Service>]/[<VirtualObject>]/[<Workflow>] types.
[<RequireQualifiedAccess>]
module Registrations =

    /// Registers every discovered service definition (mirrors the C# generator's module initializer).
    let registerAll () : unit =
        FsService.Service<TripBookingService>(
            "TripBookingService",
            FsHandler.InOut("Book", false, fun (s: TripBookingService) ctx i -> s.Book ctx i))

        FsService.VirtualObject<CounterObject>(
            "CounterObject",
            FsHandler.InOut("Add", false, fun (s: CounterObject) ctx i -> s.Add ctx i),
            FsHandler.Unit("AddThenFail", false, fun (s: CounterObject) ctx -> s.AddThenFail ctx :> System.Threading.Tasks.Task),
            FsHandler.Unit("Reset", false, fun (s: CounterObject) ctx -> s.Reset ctx :> System.Threading.Tasks.Task),
            FsHandler.Out("Get", true, fun (s: CounterObject) ctx -> s.Get ctx),
            FsHandler.Out("GetKeys", true, fun (s: CounterObject) ctx -> s.GetKeys ctx))

        FsService.Workflow<SignupWorkflow>(
            "SignupWorkflow",
            FsHandler.InOut("Run", false, fun (s: SignupWorkflow) ctx i -> s.Run ctx i),
            FsHandler.Out("GetStatus", true, fun (s: SignupWorkflow) ctx -> s.GetStatus ctx),
            FsHandler.Out("GetPendingVerificationId", true, fun (s: SignupWorkflow) ctx -> s.GetPendingVerificationId ctx))

    /// Binds every discovered service onto a host builder.
    let bind (builder: RestateHostBuilder) : RestateHostBuilder =
        builder
            .AddService<TripBookingService>()
            .AddVirtualObject<CounterObject>()
            .AddWorkflow<SignupWorkflow>()
